[es esm]

//=====================================
//WEAPONS & AMMO (TAGS, PICKUPS, OBITUARIES)
//=====================================

//Revolver ammo
XT_GOT_SPEEDLOADER		= "Recogiste un cargador rápido";
XT_TAG_SPEEDLOADER		= "Cargador rápido";

//Blue shell ammo
XT_GOT_BLUESHELLS		= "Recogiste 2 cartuchos azules";
XT_TAG_BLUESHELLS		= "Cartuchos azules";
XT_GOT_BLUESHELLBOX		= "Recogiste una caja de cartuchos azules";
XT_TAG_BLUESHELLBOX		= "Caja de cartuchos azules";

//Nail ammo
XT_GOT_NAILS			= "Recogiste algunos clavos";
XT_TAG_NAILS			= "Cargador de clavos";
XT_GOT_NAILBOX			= "Recogiste una caja de clavos";
XT_TAG_NAILBOX			= "Caja de clavos";

//Seeker ammo
XT_GOT_HSEEKER			= "Recolectaste rastreadores térmicos";
XT_TAG_HSEEKER			= "Rastreadores térmicos";
XT_GOT_TSEEKER			= "Recolectaste rastreadores tóxicos";
XT_TAG_TSEEKER			= "Rastreadores tóxicos";

//Nuke ammo
XT_GOT_NUKE				= "Recogiste una cabeza nuclear";
XT_TAG_NUKE				= "Cabeza nuclear";

//Revolver
XT_TAG_REVOLVER			= "Revólver";
XT_GOT_REVOLVER			= "¡Conseguiste el Revólver! (Ranura 2)";
XT_OB_REVOLVER			= "%o fue abatido por el Revólver de %k.";

//Ultra shotgun / Quad shotgun
XT_TAG_QUADSHOTGUN		= "Ultraescopeta";
XT_GOT_QUADSHOTGUN		= "¡Conseguiste la Ultraescopeta! (Ranura 3)";
XT_OB_QUADSHOTGUN		= "%o fue pulverizado por la Ultraescopeta de %k.";

//Assault shotgun & Striker-12
XT_TAG_ASSAULTSHOTGUN	= "Escopeta de Asalto";
XT_GOT_ASSAULTSHOTGUN	= "¡Conseguiste la Escopeta de Asalto! (Ranura 3)";
XT_OB_ASSAULTSHOTGUN	= "%o fue hecho pedazos por la Escopeta de Asalto de %k.";

XT_TAG_STRIKER12		= "Striker-12";
XT_GOT_STRIKER12		= "¡Conseguiste la Striker-12! (Ranura 3)";
XT_OB_STRIKER12			= "%o fue hecho pedazos por la Striker-12 de %k.";

//Sniper rifle
XT_TAG_SNIPERRIFLE		= "Rifle de Francotirador";
XT_GOT_SNIPERRIFLE		= "¡Conseguiste el Rifle de Francotirador! (Ranura 4)";
XT_OB_SNIPERRIFLE		= "El cerebro de %o fue esparcido por el Rifle de Francotirador de %k.";

//Light machinegun
XT_TAG_LMG				= "Ametralladora Ligera";
XT_GOT_LMG				= "¡Conseguiste la Ametralladora Ligera! (Ranura 4)";
XT_OB_LMG				= "%o fue acribillado por la Ametralladora Ligera de %k.";
XT_OB_LMGGREN			= "%o fue volado en pedazos por la granada de %k.";

//Grenade launcher
XT_TAG_NADELAUNCHER		= "Lanzagranadas";
XT_GOT_NADELAUNCHER		= "¡Conseguiste el Lanzagranadas! (Ranura 5)";
XT_OB_NADE				= "%o atrapó la granada de %k.";
XT_OB_GASNADE			= "%o fue gaseado por %k.";

//Nailgun
XT_TAG_NAILGUN			= "Lanzaclavos";
XT_GOT_NAILGUN			= "¡Conseguiste el Lanzaclavos! (Ranura 6)";
XT_OB_NAIL				= "%o fue clavado por %k.";
XT_OB_HOTNAIL			= "%o fue torturado por los clavos ardientes de %k.";

//BFG 10000
XT_TAG_BFG10K			= "BFG 10000";
XT_GOT_BFG10K			= "¡Conseguiste la BFG10000! ¡Toma ya! (Ranura 7)";
XT_OB_BFG10K			= "%o fue desintegrado por la BFG10K de %k.";

//Ruiner
XT_TAG_RUINER			= "Arruinador";
XT_GOT_RUINER			= "Sientes que te está observando... (Ranura 8)";

//Heatseeker launchers
XT_TAG_HEATSEEKER		= "Lanzadores Teledirigidos";
XT_GOT_HEATSEEKER		= "¡Conseguiste los Lanzadores Teledirigidos! (Ranura 9)";

//Flamethrower
XT_TAG_FLAMETHROWER		= "Lanzallamas";
XT_GOT_FLAMETHROWER		= "¡Conseguiste el Lanzallamas! (Ranura 9)";
XT_OB_FLAMETHROWER		= "%o fue incinerado por el lanzallamas de %k.";
XT_OB_FLAMESHOT			= "%o fue quemado por el disparo de llamas de %k.";

//Tactical nuke launcher
XT_TAG_NUKELAUNCHER		= "Lanzador Nuclear Táctico";
XT_GOT_NUKELAUNCHER		= "Recuerda: agáchate y cúbrete (Ranura 0).";
XT_OB_NUKEEXPLOSION		= "%o fue atomizado por una explosión nuclear.";
XT_OB_NUKEHEATWAVE		= "%o fue calcinado por una ola de calor nuclear.";
XT_OB_RADIATION			= "%o murió por envenenamiento por radiación.";

//Axe
XT_TAG_FIREAXE			= "Hacha";
XT_GOT_FIREAXE			= "¡Un hacha! ¡Hora de partir cabezas! (Ranura 1)";
XT_OB_FIREAXE			= "¡%o fue descuartizado por el hacha de %k!";
XT_OB_AXEPUSH			= "%o fue apaleado por %k.";
XT_OB_AXEFUCKOFF		= "%o fue mandado al demonio.";


//=====================================
//WEAPON MESSAGES & NOTIFICATIONS
//=====================================

//Standard weapon actions & prompts
WM_COCKED				= "Amartillado";				//revolver
WM_UNCOCKED				= "Desamartillado";				//revolver
WM_NEEBERSERK			= "¡Necesitas Berserk!";
WM_MAGICSEAL			= "Está sellado con magia...";

//Weapon fire / firing modes
WM_UNGUIDEDMISSILES		= "¡Misiles No Guiados!";
WM_GUIDEDMISSILES		= "¡Misiles Guiados!";
WM_BULLETMODE			= "Modo Bala";
WM_GRENADEMODE			= "Modo Granada";
WM_INCENDIARYMODE		= "¡Modo Incendiario!";
WM_NORMALMODE			= "¡Modo Normal!";

//=====================================
//POWER-UPS
//=====================================

//Arsenal sphere
XT_GOTPWR_ARSE			= "¡Munición Infinita!";
XT_TAGPWR_ARSE			= "Esfera de Arsenal";

//Quad sphere
XT_GOTPWR_QUAD			= "¡Daño Cuádruple!";
XT_TAGPWR_QUAD			= "Esfera Cuádruple";

//Nightmare sphere (speed + partial invisibility)
XT_GOTPWR_GHAST			= "¡Poder de Pesadilla!";
XT_TAGPWR_GHAST			= "Nochesfera";

//Undying sphere (vampirism + undying)
XT_GOTPWR_TITAN			= "¡Inmortalidad!";
XT_TAGPWR_TITAN			= "Esfera de Inmortalidad";

//Holy cross (infrared + monster fright)
XT_GOTPWR_HOLY			= "¡Luz de Dios!";
XT_TAGPWR_HOLY			= "Cruz Sagrada";

//Bio suit (rad suit + poison, plasma & BFG resistance)
XT_GOTPWR_BIO			= "Conseguiste un Traje Biológico";
XT_TAGPWR_BIO			= "Traje Biológico";

//Giga sphere (+300 HP/red armour)
XT_GOTPWR_ULTRA			= "¡¡Gigaesfera!!";
XT_TAGPWR_ULTRA			= "Gigaesfera";

//Red armour (+300 armour + flame resistance)
XT_GOTPWR_REDARM		= "¡Conseguiste la Ultraarmadura!";
XT_TAGPWR_REDARM		= "Armadura Roja";

//Demi sphere (+50 HP/armour)
XT_GOTPWR_MINI			= "¡Demiesfera!";
XT_TAGPWR_MINI			= "Demiesfera";

//Hyper sphere (+200 HP)
XT_GOTPWR_HYPE			= "¡¡Hipercarga!!";
XT_TAGPWR_HYPE			= "Hiperesfera";

//=====================================
//MENU DEFINITIONS (XTRAGOODIES)
//=====================================

XT_MNU_POWERUPS_OPTIONS		= "---------- Opciones de Potenciadores Extra ----------";
XT_MNU_WEAPONS_OPTIONS		= "---------- Opciones de Armas Extra ----------";

XT_MNU_SPAWNER_SPHERES		= "Generador de Esferas";
XT_MNU_SPAWNER_INFRARED		= "Generador de Visor Infrarrojo";
XT_MNU_SPAWNER_ALLMAP		= "Generador de Mapa del Área";
XT_MNU_SPAWNER_RADSUIT		= "Generador de Traje Antirradiación";
XT_MNU_SPAWNER_ARMOR		= "Generador de Armaduras";
XT_MNU_REDARMOR_DESC		= "(Armadura roja = 300 de armadura y protección contra fuego)";

XT_MNU_SPHERE_DEF			= "Predeterminado = Esferas Clásicas";
XT_MNU_INFRARED_DEF			= "Predeterminado = Infrarrojo";
XT_MNU_ALLMAP_DEF			= "Predeterminado = Mapa del Área";
XT_MNU_SUIT_DEF				= "Predeterminado = Traje Antirradiación";
XT_MNU_ARMOR_DEF			= "Predeterminado = Armadura Azul";
XT_MNU_CHAINSAW_DEF			= "Predeterminado = Motosierra";
XT_MNU_SHOTGUN_DEF			= "Predeterminado = Escopeta";
XT_MNU_SSG_DEF				= "Predeterminado = Súper Escopeta";
XT_MNU_RLAUNCHER_DEF		= "Predeterminado = Lanzacohetes";
XT_MNU_PLASMA_DEF			= "Predeterminado = Rifle de Plasma";
XT_MNU_AMMO_DEF				= "Predeterminado = Solo Munición Normal";

XT_MNU_SPAWNER_CHAINSAW		= "Generador de Motosierra";
XT_MNU_SPAWNER_SHOTGUN		= "Generador de Escopeta";
XT_MNU_SPAWNER_SSG			= "Generador de Súper Escopeta";
XT_MNU_SPAWNER_RL			= "Generador de Lanzacohetes";
XT_MNU_SPAWNER_EXTRAAMMO	= "Generador de Munición Extra";

XT_MNU_ENABLE_NUKE			= "Activar Lanzador Nuclear";
XT_MNU_NUKE_DESC1			= "Permite que los Lanzadores Nucleares aparezcan junto a la Invulnerabilidad";
XT_MNU_NUKE_DESC2			= "y las Cabezas Nucleares junto a los Cohetes/Cajas de Cohetes";

XT_MNU_STRIKER				= "Striker-12 como alternativa a la Escopeta de Asalto =";
XT_MNU_STRIKER_DESC			= "Cambiar entre Striker-12 o Escopeta de Asalto";