[ru rus]

//=====================================
//WEAPONS & AMMO (TAGS, PICKUPS, OBITUARIES)
//=====================================

//Revolver ammo
XT_GOT_SPEEDLOADER		= "Вы подобрали спидлоадер";
XT_TAG_SPEEDLOADER		= "Спидлоадер";

//Blue shell ammo
XT_GOT_BLUESHELLS		= "Вы подобрали 2 синих патрона";
XT_TAG_BLUESHELLS		= "Синие патроны";
XT_GOT_BLUESHELLBOX		= "Вы подобрали коробку синих патронов";
XT_TAG_BLUESHELLBOX		= "Коробка синих патронов";

//Nail ammo
XT_GOT_NAILS			= "Вы подобрали гвозди";
XT_TAG_NAILS			= "Магазин с гвоздями";
XT_GOT_NAILBOX			= "Вы подобрали коробку гвоздей";
XT_TAG_NAILBOX			= "Коробка гвоздей";

//Seeker ammo
XT_GOT_HSEEKER			= "Вы нашли самонаводящиеся ракеты";
XT_TAG_HSEEKER			= "Тепловые ракеты";
XT_GOT_TSEEKER			= "Вы нашли токсичные ракеты";
XT_TAG_TSEEKER			= "Токсичные ракеты";

//Nuke ammo
XT_GOT_NUKE				= "Вы подобрали ядерную боеголовку";
XT_TAG_NUKE				= "Ядерная боеголовка";

//Revolver
XT_TAG_REVOLVER			= "Револьвер";
XT_GOT_REVOLVER			= "Вы получили Револьвер! (Слот 2)";
XT_OB_REVOLVER			= "%o был застрелен из Револьвера %k.";

//Ultra shotgun / Quad shotgun
XT_TAG_QUADSHOTGUN		= "Ультра-дробовик";
XT_GOT_QUADSHOTGUN		= "Вы получили Ультра-дробовик! (Слот 3)";
XT_OB_QUADSHOTGUN		= "%o был уничтожен Ультра-дробовиком %k.";

//Assault shotgun & Striker-12
XT_TAG_ASSAULTSHOTGUN	= "Штурмовой дробовик";
XT_GOT_ASSAULTSHOTGUN	= "Вы получили Штурмовой дробовик! (Слот 3)";
XT_OB_ASSAULTSHOTGUN	= "%o был разорван на куски Штурмовым дробовиком %k.";

XT_TAG_STRIKER12		= "Striker-12";
XT_GOT_STRIKER12		= "Вы получили Striker-12! (Слот 3)";
XT_OB_STRIKER12			= "%o был разорван на куски из Striker-12 %k.";

//Sniper rifle
XT_TAG_SNIPERRIFLE		= "Снайперская винтовка";
XT_GOT_SNIPERRIFLE		= "Вы получили Снайперскую винтовку! (Слот 4)";
XT_OB_SNIPERRIFLE		= "Мозги %o были размазаны Снайперской винтовкой %k.";

//Light machinegun
XT_TAG_LMG				= "Ручной пулемёт";
XT_GOT_LMG				= "Вы получили Ручной пулемёт! (Слот 4)";
XT_OB_LMG				= "%o был скошен Ручным пулемётом %k.";
XT_OB_LMGGREN			= "%o подорвался на гранате пулемёта %k.";

//Grenade launcher
XT_TAG_NADELAUNCHER		= "Гранатомёт";
XT_GOT_NADELAUNCHER		= "Вы получили Гранатомёт! (Слот 5)";
XT_OB_NADE				= "%o поймал гранату %k.";
XT_OB_GASNADE			= "%o был отравлен газом %k.";

//Nailgun
XT_TAG_NAILGUN			= "Гвоздемёт";
XT_GOT_NAILGUN			= "Вы получили Гвоздемёт! (Слот 6)";
XT_OB_NAIL				= "%o был пригвождён %k.";
XT_OB_HOTNAIL			= "%o был замучен пылающими гвоздями %k.";

//BFG 10000
XT_TAG_BFG10K			= "BFG 10000";
XT_GOT_BFG10K			= "Вы получили BFG10000! Вот это да! (Слот 7)";
XT_OB_BFG10K			= "%o был испепелён BFG10K %k.";

//Ruiner
XT_TAG_RUINER			= "Разрушитель";
XT_GOT_RUINER			= "Вы чувствуете, что оно следит за вами... (Слот 8)";

//Heatseeker launchers
XT_TAG_HEATSEEKER		= "Самонаводящиеся установки";
XT_GOT_HEATSEEKER		= "Вы получили Самонаводящиеся установки! (Слот 9)";

//Flamethrower
XT_TAG_FLAMETHROWER		= "Огнемёт";
XT_GOT_FLAMETHROWER		= "Вы получили Огнемёт! (Слот 9)";
XT_OB_FLAMETHROWER		= "%o был кремирован огнемётом %k.";
XT_OB_FLAMESHOT			= "%o сгорел от огненного выстрела %k.";

//Tactical nuke launcher
XT_TAG_NUKELAUNCHER		= "Тактическая ядерная установка";
XT_GOT_NUKELAUNCHER		= "Помните — Вспышка сзади, ложись! (Слот 0).";
XT_OB_NUKEEXPLOSION		= "%o был расщеплён ядерным взрывом.";
XT_OB_NUKEHEATWAVE		= "%o сгорел в ядерной тепловой волне.";
XT_OB_RADIATION			= "%o умер от лучевой болезни.";

//Axe
XT_TAG_FIREAXE			= "Топор";
XT_GOT_FIREAXE			= "Топор! Время рубить! (Слот 1)";
XT_OB_FIREAXE			= "%o был зарублен топором %k!";
XT_OB_AXEPUSH			= "%o был избит %k.";
XT_OB_AXEFUCKOFF		= "%o был отправлен на тот свет.";


//=====================================
//WEAPON MESSAGES & NOTIFICATIONS
//=====================================

//Standard weapon actions & prompts
WM_COCKED				= "Взведен";					//revolver
WM_UNCOCKED				= "Спущен";						//revolver
WM_NEEBERSERK			= "Нужен Берсерк!";
WM_MAGICSEAL			= "Запечатано магической печатью...";

//Weapon fire / firing modes
WM_UNGUIDEDMISSILES		= "Неуправляемые ракеты!";
WM_GUIDEDMISSILES		= "Управляемые ракеты!";
WM_BULLETMODE			= "Режим пуль";
WM_GRENADEMODE			= "Режим гранат";
WM_INCENDIARYMODE		= "Зажигательный режим!";
WM_NORMALMODE			= "Обычный режим!";

//=====================================
//POWER-UPS
//=====================================

//Arsenal sphere
XT_GOTPWR_ARSE			= "Бесконечные патроны!";
XT_TAGPWR_ARSE			= "Сфера Арсенала";

//Quad sphere
XT_GOTPWR_QUAD			= "Четверной урон!";
XT_TAGPWR_QUAD			= "Сфера Квада";

//Nightmare sphere (speed + partial invisibility)
XT_GOTPWR_GHAST			= "Сила Кошмара!";
XT_TAGPWR_GHAST			= "Сфера Ночи";

//Undying sphere (vampirism + undying)
XT_GOTPWR_TITAN			= "Бессмертие!";
XT_TAGPWR_TITAN			= "Сфера Бессмертия";

//Holy cross (infrared + monster fright)
XT_GOTPWR_HOLY			= "Божественный свет!";
XT_TAGPWR_HOLY			= "Святой Крест";

//Bio suit (rad suit + poison, plasma & BFG resistance)
XT_GOTPWR_BIO			= "Вы получили Биокостюм";
XT_TAGPWR_BIO			= "Биологический костюм";

//Giga sphere (+300 HP/red armour)
XT_GOTPWR_ULTRA			= "Гигасфера!!";
XT_TAGPWR_ULTRA			= "Гигасфера";

//Red armour (+300 armour + flame resistance)
XT_GOTPWR_REDARM		= "Вы получили Ультра-броню!";
XT_TAGPWR_REDARM		= "Красная броня";

//Demi sphere (+50 HP/armour)
XT_GOTPWR_MINI			= "Демисфера!";
XT_TAGPWR_MINI			= "Демисфера";

//Hyper sphere (+200 HP)
XT_GOTPWR_HYPE			= "Гиперзаряд!!";
XT_TAGPWR_HYPE			= "Гиперсфера";

//=====================================
//MENU DEFINITIONS (XTRAGOODIES)
//=====================================

XT_MNU_POWERUPS_OPTIONS		= "\c[Orange]---------- Доп. опции бонусов ----------";
XT_MNU_WEAPONS_OPTIONS		= "\c[Orange]---------- Доп. опции оружия ----------";

XT_MNU_SPAWNER_SPHERES		= "Спавнер сфер";
XT_MNU_SPAWNER_INFRARED		= "Спавнер ИК-визора";
XT_MNU_SPAWNER_ALLMAP		= "Спавнер карты местности";
XT_MNU_SPAWNER_RADSUIT		= "Спавнер костюма";
XT_MNU_SPAWNER_ARMOR		= "Спавнер брони";
XT_MNU_REDARMOR_DESC		= "(Красная броня = 300 брони и защита от огня)";

XT_MNU_SPHERE_DEF			= "По умолчанию = Классические сферы";
XT_MNU_INFRARED_DEF			= "По умолчанию = ИК-визор";
XT_MNU_ALLMAP_DEF			= "По умолчанию = Карта местности";
XT_MNU_SUIT_DEF				= "По умолчанию = Костюм";
XT_MNU_ARMOR_DEF			= "По умолчанию = Синяя броня";
XT_MNU_CHAINSAW_DEF			= "По умолчанию = Бензопила";
XT_MNU_SHOTGUN_DEF			= "По умолчанию = Дробовик";
XT_MNU_SSG_DEF				= "По умолчанию = Двустволка";
XT_MNU_RLAUNCHER_DEF		= "По умолчанию = Ракетомёт";
XT_MNU_PLASMA_DEF			= "По умолчанию = Плазмоган";
XT_MNU_AMMO_DEF				= "По умолчанию = Только обычные патроны";

XT_MNU_SPAWNER_CHAINSAW		= "Спавнер бензопилы";
XT_MNU_SPAWNER_SHOTGUN		= "Спавнер дробовика";
XT_MNU_SPAWNER_SSG			= "Спавнер двустволки";
XT_MNU_SPAWNER_RL			= "Спавнер ракетомёта";
XT_MNU_SPAWNER_EXTRAAMMO	= "Спавнер доп. патронов";

XT_MNU_ENABLE_NUKE			= "Включить ядерную установку";
XT_MNU_NUKE_DESC1			= "Разрешить спавн ядерных установок вместе с неуязвимостью";
XT_MNU_NUKE_DESC2			= "и ядерных боеголовок вместе с ракетами/ящиками ракет";

XT_MNU_STRIKER				= "Striker-12 как альтернатива штурмовому дробовику =";
XT_MNU_STRIKER_DESC			= "Переключение между Striker-12 и штурмовым дробовиком";