#library "XTRAPACK"
#import "zcommon.bcs"
#include "BCSFunc.acs"

//WEAPON CVAR CHECKERS
script "ChainsawSpawner" (void)
{
	SetResultValue(GetCvar("Chainsaw_Spawner_Cvar"));
}

script "ShotgunSpawner" (void)
{
	SetResultValue(GetCvar("Revolver_Spawner_Cvar"));
}

script "SSGSpawner" (void)
{
	SetResultValue(GetCvar("AutoShotgun_Spawner_Cvar"));
}

script "ChaingunExtraSpawner" (void)
{
	SetResultValue(GetCvar("Chaingun_Spawner_Cvar"));
}

script "RLSpawner" (void)
{
	SetResultValue(GetCvar("Immolator_Spawner_Cvar"));
}

script "PlasmaRifleExtraSpawner" (void)
{
	SetResultValue(GetCvar("GaussCannon_Spawner_Cvar"));
}

script "BFGExtraSpawner" (void)
{
	SetResultValue(GetCvar("BFG_Spawner_Cvar"));
}

//AMMO & POWERUP CVAR CHECKERS
script "ExtraAmmoRandomACS" (void)
{
	SetResultValue(GetCvar("ExtraAmmo_Spawner_Cvar"));
}

script "NukelauncherSpawnerACS" (void)
{
	SetResultValue(GetCvar("NuclearMissile_Spawner_Cvar"));
}

script "ExtraSpheresACS" (void)
{
	SetResultValue(GetCvar("ExtraSpheres_CVar"));
}

script "InfraredNewRandomACS" (void)
{
	SetResultValue(GetCvar("Crucifix_Spawner_CVar"));
}

script "AllMapNewRandomACS" (void)
{
	SetResultValue(GetCvar("MapRadar_Spawner_CVar"));
}

script "BlueArmorsNewRandomACS" (void)
{
	SetResultValue(GetCvar("RedArmor_Spawner_CVar"));
}

script "RadsuitNewRandomACS" (void)
{
	SetResultValue(GetCvar("Biosuit_Spawner_CVar"));
}

script "WpnPowerExtra" (void)
{
	SetResultValue(GetCvar("WpnPower_Spawner_Cvar"));
}

//UTILITY & PRESET SCRIPTS
script "Striker12ACS" Enter
{
	if(GetCvar("Striker12Cvar") == 1)
	{
		SetActorState(0,"ShowStriker12");
	}

	SetInventory("ProtectaSwitchToken",GetCvar("Striker12Cvar"));
	Delay(64);
	Restart;
}

script "PlayerDeathScript" Death
{
	Delay(1);
	TakeInventory("ClassicChainsawToken",1);
	TakeInventory("ClassicRLToken",1);
	TakeInventory("ProtectaSwitchToken",1);
}

script "ExtraOriginalCvars" (void) net
{
	SetCvar("ExtraSpheres_CVar",1);
	SetCvar("Crucifix_Spawner_CVar",1);
	SetCvar("MapRadar_Spawner_CVar",1);
	SetCvar("Biosuit_Spawner_CVar",1);
	SetCvar("RedArmor_Spawner_CVar",1);
	SetCvar("Chainsaw_Spawner_Cvar",1);
	SetCvar("Revolver_Spawner_Cvar",1);
	SetCvar("AutoShotgun_Spawner_Cvar",1);
	SetCvar("Immolator_Spawner_Cvar",1);
	SetCvar("NuclearMissile_Spawner_Cvar",0);
	SetCvar("ExtraAmmo_Spawner_Cvar",1);
	SetCvar("Striker12Cvar",0);	
	ACS_NamedExecuteAlways("OriginalCvars",0);
}

script "ExtraClassicCvars" (void) net
{
	SetCvar("ExtraSpheres_CVar",1);
	SetCvar("Crucifix_Spawner_CVar",1);
	SetCvar("MapRadar_Spawner_CVar",1);
	SetCvar("Biosuit_Spawner_CVar",1);
	SetCvar("RedArmor_Spawner_CVar",1);
	SetCvar("Chainsaw_Spawner_Cvar",1);
	SetCvar("Revolver_Spawner_Cvar",1);
	SetCvar("AutoShotgun_Spawner_Cvar",1);
	SetCvar("Immolator_Spawner_Cvar",1);
	SetCvar("NuclearMissile_Spawner_Cvar",0);
	SetCvar("ExtraAmmo_Spawner_Cvar",1);
	SetCvar("Striker12Cvar",0);	
	ACS_NamedExecuteAlways("ClassicCvars",0);
}

script "ExtraEnhancedCvars" (void) net
{
	SetCvar("ExtraSpheres_CVar",2);
	SetCvar("Crucifix_Spawner_CVar",1);
	SetCvar("MapRadar_Spawner_CVar",2);
	SetCvar("Biosuit_Spawner_CVar",2);
	SetCvar("RedArmor_Spawner_CVar",1);
	SetCvar("Chainsaw_Spawner_Cvar",1);
	SetCvar("Revolver_Spawner_Cvar",1);
	SetCvar("AutoShotgun_Spawner_Cvar",1);
	SetCvar("Immolator_Spawner_Cvar",1);
	SetCvar("NuclearMissile_Spawner_Cvar",1);
	SetCvar("ExtraAmmo_Spawner_Cvar",2);
	SetCvar("Striker12Cvar",1);	
	ACS_NamedExecuteAlways("EnhancedCvars",0);
}

script "ExtraRandomCvars" (void) net
{
	SetCvar("ExtraSpheres_CVar",0);
	SetCvar("Crucifix_Spawner_CVar",0);
	SetCvar("MapRadar_Spawner_CVar",0);
	SetCvar("Biosuit_Spawner_CVar",0);
	SetCvar("RedArmor_Spawner_CVar",0);
	SetCvar("Chainsaw_Spawner_Cvar",0);
	SetCvar("Revolver_Spawner_Cvar",0);
	SetCvar("AutoShotgun_Spawner_Cvar",0);
	SetCvar("Immolator_Spawner_Cvar",0);
	SetCvar("NuclearMissile_Spawner_Cvar",0);
	SetCvar("ExtraAmmo_Spawner_Cvar",random(-1,0));
	SetCvar("Striker12Cvar",0);	
	ACS_NamedExecuteAlways("RandomCvars",0);
}