#library "XTRAPACK"
#import "zcommon.bcs"
#include "BCSFunc.acs"

//WEAPON CVAR CHECKERS
script "ChainsawSpawner" (void)
{
	SetResultValue(GetCvar("Chainsaw_Spawner_Cvar"));
}

script "ShotgunSpawner" (void)
{
	SetResultValue(GetCvar("Revolver_Spawner_Cvar"));
}

script "SSGSpawner" (void)
{
	SetResultValue(GetCvar("AutoShotgun_Spawner_Cvar"));
}

script "ChaingunExtraSpawner" (void)
{
	SetResultValue(GetCvar("Chaingun_Spawner_Cvar"));
}

script "RLSpawner" (void)
{
	SetResultValue(GetCvar("Immolator_Spawner_Cvar"));
}

script "PlasmaRifleExtraSpawner" (void)
{
	SetResultValue(GetCvar("GaussCannon_Spawner_Cvar"));
}

script "BFGExtraSpawner" (void)
{
	SetResultValue(GetCvar("BFG_Spawner_Cvar"));
}

//AMMO & POWERUP CVAR CHECKERS
script "ExtraAmmoRandomACS" (void)
{
	SetResultValue(GetCvar("ExtraAmmo_Spawner_Cvar"));
}

script "NukelauncherSpawnerACS" (void)
{
	SetResultValue(GetCvar("NuclearMissile_Spawner_Cvar"));
}

script "ExtraSpheresACS" (void)
{
	SetResultValue(GetCvar("ExtraSpheres_CVar"));
}

script "InfraredNewRandomACS" (void)
{
	SetResultValue(GetCvar("Crucifix_Spawner_CVar"));
}

script "AllMapNewRandomACS" (void)
{
	SetResultValue(GetCvar("MapRadar_Spawner_CVar"));
}

script "BlueArmorsNewRandomACS" (void)
{
	SetResultValue(GetCvar("RedArmor_Spawner_CVar"));
}

script "RadsuitNewRandomACS" (void)
{
	SetResultValue(GetCvar("Biosuit_Spawner_CVar"));
}

script "WpnPowerExtra" (void)
{
	SetResultValue(GetCvar("WpnPower_Spawner_Cvar"));
}

//UTILITY & PRESET SCRIPTS
script "CheckStriker12CvarACS" (void)
{
	SetResultValue(GetCvar("Striker12Cvar"));
}

script "ProtectaSwitchACS" (int activeIsProtecta,int isTactical)
{
	int SwitchWeapon = GetCVar("Striker12Cvar");

	if (isTactical) //Tactical class variant
	{
		if (!activeIsProtecta && SwitchWeapon)	//from assault to protecta
		{
			GiveInventory("64ProtectaTactical",1);
			SetWeapon("64ProtectaTactical");
			TakeInventory("64AssaultShotgunTactical",1);
			SetResultValue(1);
		}
		else if (activeIsProtecta && !SwitchWeapon)	//from protecta to assault
		{
			int shellCount = CheckInventory("64BlueShell");
			GiveInventory("64AssaultShotgunTactical",1);
			SetInventory("64BlueShell",shellCount);
			SetWeapon("64AssaultShotgunTactical");
			TakeInventory("64ProtectaTactical",1);
			SetResultValue(1);
		}
		else
		{
			SetResultValue(0);
		}
	}
	else //Classic class variant
	{
		if (!activeIsProtecta && SwitchWeapon)
		{
			GiveInventory("64Protecta",1);
			SetWeapon("64Protecta");
			TakeInventory("64AssaultShotgun",1);
			SetResultValue(1);
		}
		else if (activeIsProtecta && !SwitchWeapon)
		{
			GiveInventory("64AssaultShotgun",1);
			SetWeapon("64AssaultShotgun");
			TakeInventory("64Protecta",1);
			SetResultValue(1);
		}
		else
		{
			SetResultValue(0);
		}
	}
}

script "ExtraOriginalCvars" (void) net
{
	SetCvar("ExtraSpheres_CVar",1);
	SetCvar("Crucifix_Spawner_CVar",1);
	SetCvar("MapRadar_Spawner_CVar",1);
	SetCvar("Biosuit_Spawner_CVar",1);
	SetCvar("RedArmor_Spawner_CVar",1);
	SetCvar("Chainsaw_Spawner_Cvar",1);
	SetCvar("Revolver_Spawner_Cvar",1);
	SetCvar("AutoShotgun_Spawner_Cvar",1);
	SetCvar("Immolator_Spawner_Cvar",1);
	SetCvar("NuclearMissile_Spawner_Cvar",0);
	SetCvar("ExtraAmmo_Spawner_Cvar",1);
	SetCvar("Striker12Cvar",0);	
	ACS_NamedExecuteAlways("OriginalCvars",0);
}

script "ExtraClassicCvars" (void) net
{
	SetCvar("ExtraSpheres_CVar",1);
	SetCvar("Crucifix_Spawner_CVar",1);
	SetCvar("MapRadar_Spawner_CVar",1);
	SetCvar("Biosuit_Spawner_CVar",1);
	SetCvar("RedArmor_Spawner_CVar",1);
	SetCvar("Chainsaw_Spawner_Cvar",1);
	SetCvar("Revolver_Spawner_Cvar",1);
	SetCvar("AutoShotgun_Spawner_Cvar",1);
	SetCvar("Immolator_Spawner_Cvar",1);
	SetCvar("NuclearMissile_Spawner_Cvar",0);
	SetCvar("ExtraAmmo_Spawner_Cvar",1);
	SetCvar("Striker12Cvar",0);	
	ACS_NamedExecuteAlways("ClassicCvars",0);
}

script "ExtraEnhancedCvars" (void) net
{
	SetCvar("ExtraSpheres_CVar",2);
	SetCvar("Crucifix_Spawner_CVar",1);
	SetCvar("MapRadar_Spawner_CVar",2);
	SetCvar("Biosuit_Spawner_CVar",2);
	SetCvar("RedArmor_Spawner_CVar",1);
	SetCvar("Chainsaw_Spawner_Cvar",1);
	SetCvar("Revolver_Spawner_Cvar",1);
	SetCvar("AutoShotgun_Spawner_Cvar",1);
	SetCvar("Immolator_Spawner_Cvar",1);
	SetCvar("NuclearMissile_Spawner_Cvar",1);
	SetCvar("ExtraAmmo_Spawner_Cvar",2);
	SetCvar("Striker12Cvar",1);	
	ACS_NamedExecuteAlways("EnhancedCvars",0);
}

script "ExtraRandomCvars" (void) net
{
	SetCvar("ExtraSpheres_CVar",0);
	SetCvar("Crucifix_Spawner_CVar",0);
	SetCvar("MapRadar_Spawner_CVar",0);
	SetCvar("Biosuit_Spawner_CVar",0);
	SetCvar("RedArmor_Spawner_CVar",0);
	SetCvar("Chainsaw_Spawner_Cvar",0);
	SetCvar("Revolver_Spawner_Cvar",0);
	SetCvar("AutoShotgun_Spawner_Cvar",0);
	SetCvar("Immolator_Spawner_Cvar",0);
	SetCvar("NuclearMissile_Spawner_Cvar",0);
	SetCvar("ExtraAmmo_Spawner_Cvar",random(-1,0));
	SetCvar("Striker12Cvar",0);	
	ACS_NamedExecuteAlways("RandomCvars",0);
}